### ISSUE TITLE
recognize the admin role

### ISSUE THREAD

**Issue by ghost** [gvlekke/MysticDiscord#1]
We now have the following code for letting a moderator give the mystic role to new players:

```
 if (message.content.startsWith('!add')) {
    if (message.member.roles.has(moderator)) {
      let member = message.mentions.members.first();
      let role = message.guild.roles.find("name", "makingdelftblueagain");
      member.addRole(role).catch(console.error);
      message.channel.send('Welkom ' + member + ', je bent nu officieel toegevoegd! In het kanaal #welkom is te lezen hoe deze discord werkt, lees dat dus vooral eens door! ;)');
    } else {
      message.reply('Leden verifieren kan alleen door een moderator worden gedaan')
    }
    message.delete()
} else
```

For some reason i don't understand i can let the bot search for the "makingdelftblueagain" role, but not for the "moderators" role. As a result we have to put the "moderators" roleID in a seperate file, and because of that we can not test moderator functions on our test discord (since the "moderators" role has a different roleID)

**Comment by petiebarie** [comment]
This is fixed
