### ISSUE TITLE
raids - +x functie

### ISSUE THREAD

**Issue by petiebarie** [gvlekke/MysticDiscord#34]
Het is een stuk overzichtelijker als iemand een +x achter zijn naam krijgt als hij meerdere keren op de "+" klikt. Ook is dit minder verwarrend als er naar speler levels gekeken wordt. Als een lvl 40 speler 2 aanhang meeneemt hoeven die natuurlijk niet beide ook lvl 40 te zijn.

**Comment by daanschipper** [comment]
From the discussion in discord the following method is chosen:
- upon new raid: notification with `raid 1: @[pokemon]`
- upon joining: message with `player a has joined raid 1`
- upon another player joining: first message gets deleted, new message with `player b and player b have joined raid 1`
- more people join: new message becomes `player e, player d and 3 other have joined raid 1`

**Comment by petiebarie** [comment]
I think @daanschipper is responding to another issue, but i would do it as follows:

upon new raid: notification with raid 1: @[pokemon]
upon joining: message with "Raid 1 (1): [playername] joined
upon another player joining: first message gets deleted, new message: 
raid 1 (2): [playername joined]
etc
